name: insudocs
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  age_calculator: ^1.0.0
  cloud_firestore: ^3.5.1
  file_picker: ^5.2.1
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  firebase_database: ^9.1.7
  firebase_messaging: ^13.1.0
  firebase_storage: ^10.3.11
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.4
  flutter_firebase_chat_core: ^1.6.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.5
  google_sign_in: ^5.4.2
  shared_preferences: ^2.0.15
  syncfusion_flutter_charts: ^20.3.49
  url_launcher: ^6.1.6
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/images/login_types/

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Italic.ttf
          style: italic

    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.otf
        - asset: assets/fonts/Cabin-Italic.otf
          style: italic
