// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ0edXNB6yUz_GpPqW-EsQZAEtxo3kVmE',
    appId: '1:703023409278:web:becc1011b09bd76605102f',
    messagingSenderId: '703023409278',
    projectId: 'insudox',
    authDomain: 'insudox.firebaseapp.com',
    databaseURL:
        'https://insudox-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'insudox.appspot.com',
    measurementId: 'G-CW8ZED552P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa-jcmfnyn4uEeZGj8U88GxcwDtUf51KI',
    appId: '1:703023409278:android:bbf18f5438e16b1905102f',
    messagingSenderId: '703023409278',
    projectId: 'insudox',
    databaseURL:
        'https://insudox-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'insudox.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtiHcy14LWYbOS8ueGPfa7ceDqd2BzS4w',
    appId: '1:703023409278:ios:78ae74888ce3b52305102f',
    messagingSenderId: '703023409278',
    projectId: 'insudox',
    databaseURL:
        'https://insudox-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'insudox.appspot.com',
    androidClientId:
        '703023409278-6lmjblvogr7j1r5t8tjonlle19otjo9h.apps.googleusercontent.com',
    iosClientId:
        '703023409278-khfmfm3d78b8svk2u02ukta1lgj588fi.apps.googleusercontent.com',
    iosBundleId: 'com.rushour-tech.insudoxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtiHcy14LWYbOS8ueGPfa7ceDqd2BzS4w',
    appId: '1:703023409278:ios:78ae74888ce3b52305102f',
    messagingSenderId: '703023409278',
    projectId: 'insudox',
    databaseURL:
        'https://insudox-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'insudox.appspot.com',
    androidClientId:
        '703023409278-6lmjblvogr7j1r5t8tjonlle19otjo9h.apps.googleusercontent.com',
    iosClientId:
        '703023409278-khfmfm3d78b8svk2u02ukta1lgj588fi.apps.googleusercontent.com',
    iosBundleId: 'com.rushour-tech.insudoxApp',
  );
}
